# http://travis-ci.org/#!/mozilla/popcoder

# This indicates to Travis that we will not use or need sudo
# so that we can benefit from and use the cache->directories
# directive.
sudo: no

language: python

python:
  - 2.6
  - 2.7

# Hmm...???
# https://github.com/phaux/node-ffmpeg-stream/blob/master/.travis.yml

script:
  - python setup.py test

notifications:
  irc:
    channels: "irc.mozilla.org#airmozilla-dev"

deploy:
  provider: pypi
  user: peterbe
  password:
    secure: N4eEiY/L+LeGDaCw7EowDAohUr////qB5LR8vIFvrt21/K2f258LeBJIYSbUWsuHacjCT6PFRSeH7lK5/L+QChDdlCb3z5ctzpPxd5ga65HTpHgGJzgqY/8A85$
  on:
    repo: mozilla/popcoder
  distributions: "sdist bdist_wheel"
